# Generated by Django 4.1.1 on 2022-10-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='news.news', verbose_name='News'),
        ),
    ]
