# Generated by Django 4.1.1 on 2022-10-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comments_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='news.news', verbose_name='News'),
        ),
    ]
